from __future__ import annotations

import os
import re
from datetime import datetime, timezone

import structlog

from agent_ls import __version__
from agent_ls.config.settings import get_settings
from agent_ls.graph.state import AgentState, PlanStep
from agent_ls.integrations.obsidian.git_sync import GitSync
from agent_ls.integrations.obsidian.vault import ObsidianVault

logger = structlog.get_logger()

_WARNING = (
    "# WARNING: This script was auto-generated. Review before running. Commands that\n"
    "# failed or were blocked during agent execution are commented out."
)


def _sanitize_comment(text: str) -> str:
    """Collapse newlines/carriage-returns so metadata stays on a single # line.

    All interpolated metadata (descriptions, commands shown in notes) is placed on
    a `#`-prefixed line; flattening to one line prevents hostile content from
    breaking out of the comment and becoming an executable line.
    """
    return text.replace("\r", " ").replace("\n", " ")


def _redact_secrets(command: str, secrets: list[str]) -> str:
    """Replace each known secret value with ***REDACTED*** (defense-in-depth)."""
    for secret in secrets:
        if secret:
            command = command.replace(secret, "***REDACTED***")
    return command


def _clean(text: str, secrets: list[str]) -> str:
    """Redact secrets AND flatten newlines for any metadata rendered on a # line.

    Descriptions and notes come from LLM-generated plan prose / error-recovery text,
    so they must be redacted (a token echoed into a description would otherwise leak
    into the script) as well as newline-sanitized (so hostile content can't break out
    of the comment onto an executable line).
    """
    return _sanitize_comment(_redact_secrets(text, secrets))


def render_harness(
    plan: list[PlanStep],
    *,
    team: str,
    date: str,
    source: str,
    version: str,
    secrets: list[str],
) -> str:
    """Serialize an executed plan into a standalone, re-runnable bash harness.

    Live commands (command is not None, status == 'done', exit_code == 0) are emitted
    verbatim; every other case is emitted as a commented-out line with a precise note.
    Pure function: no I/O, no subprocess, no settings access. Returns the full script
    text ending with a trailing newline.
    """
    lines: list[str] = [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        "",
        f"# Setup harness for team: {_sanitize_comment(team)}",
        f"# Date: {_sanitize_comment(date)}",
        f"# Generated by agent-ls v{version}",
        f"# Source: {_sanitize_comment(source)}",
        _WARNING,
        "",
    ]

    for step in plan:
        lines.append(f"# {_clean(step.description, secrets)}")
        if step.command is None:
            lines.append(f"# MANUAL STEP: {_clean(step.description, secrets)}")
        elif step.status == "done" and step.exit_code == 0:
            lines.append(_redact_secrets(step.command, secrets))
        else:
            note = _clean(step.command, secrets)
            if step.status == "failed" and step.exit_code is None:
                lines.append(f"# BLOCKED: {note}")
            elif step.status == "failed":
                lines.append(f"# SKIPPED (failed, exit={step.exit_code}): {note}")
            else:
                lines.append(f"# SKIPPED ({step.status}): {note}")
        lines.append("")

    return "\n".join(lines) + "\n"


async def emit_harness_node(state: AgentState) -> dict:
    vault = ObsidianVault()
    user_context = state.get("user_context")
    team = (user_context.team if user_context else None) or "general"
    date = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    # `team` originates from untrusted Slack profile text extracted by an LLM and is
    # never validated upstream. Slugify it so path separators (and any other unsafe
    # characters) cannot escape the logs/ directory when building the harness path.
    safe_team = re.sub(r"[^A-Za-z0-9_.-]", "_", team) or "general"

    base = f"logs/{safe_team}-setup-{date}"
    rel = f"{base}.sh"
    if vault.exists(rel):
        for n in range(1, 1000):
            candidate = f"{base}-{n:03d}.sh"
            if not vault.exists(candidate):
                rel = candidate
                break

    settings = get_settings()
    # Only true credentials are redacted. The Bedrock endpoint URL is NOT a secret:
    # it is a legitimate substring of live commands (e.g. `curl <endpoint>/v1/models`),
    # and substring-replacing it would silently corrupt re-runnable commands.
    secrets = [
        v
        for v in (
            settings.bedrock.auth_token,
            settings.slack.user_token,
        )
        if v
    ]

    plan = state.get("plan", [])
    content = render_harness(
        plan,
        team=team,
        date=date,
        source="reproduced from agent-ls setup run",
        version=__version__,
        secrets=secrets,
    )

    # Defense-in-depth: confirm the resolved target stays inside logs/ before writing an
    # executable file, so no unsanitized input can drop a runnable script outside the vault.
    logs_root = (vault.root / "logs").resolve()
    if not (vault.root / rel).resolve().is_relative_to(logs_root):
        logger.error("harness_path_invalid", rel=rel)
        return {"error": "invalid harness path"}

    try:
        path = vault.write(rel, content)
        os.chmod(path, 0o755)
    except OSError as e:
        logger.error("harness_write_failed", error=str(e))
        return {"error": f"harness_write_failed: {e}"}

    if settings.obsidian.git_auto_sync:
        try:
            git_sync = GitSync(vault.root)
            if state.get("run_success"):
                git_sync.commit_and_push(path, f"agent-ls: setup harness {date}")
            else:
                git_sync.commit_file(path, f"agent-ls: setup harness {date}")
        except (ValueError, Exception) as e:
            logger.warning("git_sync_failed", error=str(e))

    live = sum(
        1 for s in plan if s.command and s.status == "done" and s.exit_code == 0
    )
    logger.info(
        "harness_emitted",
        team=team,
        filename=rel,
        step_count=len(plan),
        live_count=live,
    )

    obsidian_docs = list(state.get("obsidian_docs", []))
    obsidian_docs.append(str(path))
    return {"obsidian_docs": obsidian_docs, "harness_path": str(path)}
