import stat
from unittest.mock import MagicMock, patch

import pytest

from agent_ls.graph.nodes.emit_harness import emit_harness_node, render_harness
from agent_ls.graph.state import PlanStep, UserContext


def _live_step() -> PlanStep:
    return PlanStep(
        description="Install node",
        command="brew install node",
        status="done",
        exit_code=0,
        duration_ms=1000,
    )


def _failed_step() -> PlanStep:
    return PlanStep(
        description="Install java",
        command="brew install java",
        status="failed",
        exit_code=1,
    )


def _blocked_step() -> PlanStep:
    return PlanStep(
        description="Wipe disk",
        command="rm -rf /",
        status="failed",
        exit_code=None,
    )


def _manual_step() -> PlanStep:
    return PlanStep(
        description="Request VPN access from IT",
        command=None,
        status="skipped",
    )


@pytest.fixture
def write_state():
    from langchain_core.messages import HumanMessage

    return {
        "messages": [HumanMessage(content="setup")],
        "user_context": UserContext(team="payments"),
        "intent": "setup",
        "plan": [_live_step(), _failed_step(), _blocked_step(), _manual_step()],
        "current_step": 4,
        "execution_log": [],
        "approval_pending": None,
        "obsidian_docs": [],
        "slack_results": [],
        "error": None,
        "share_channel": None,
        "share_result": None,
        "extracted_urls": [],
        "processed_message_ids": [],
        "run_success": False,
    }


# --- Serializer tests (pure function, no mocks) ---


def _render(plan, **overrides):
    kwargs = {
        "team": "payments",
        "date": "2026-07-04",
        "source": "reproduced from agent-ls setup run",
        "version": "0.1.0",
        "secrets": [],
    }
    kwargs.update(overrides)
    return render_harness(plan, **kwargs)


def test_header_contains_required_markers():
    out = _render([_live_step()])
    assert out.startswith("#!/usr/bin/env bash\n")
    assert "set -euo pipefail" in out
    assert "# Setup harness for team: payments" in out
    assert "# Date: 2026-07-04" in out
    assert "# Generated by agent-ls v0.1.0" in out
    assert "# Source: reproduced from agent-ls setup run" in out
    assert "auto-generated" in out
    assert out.endswith("\n")


def test_live_step_is_uncommented_with_description_comment():
    out = _render([_live_step()])
    lines = out.splitlines()
    assert "# Install node" in lines
    assert "brew install node" in lines
    # The command line itself is not commented out.
    idx = lines.index("brew install node")
    assert not lines[idx].startswith("#")


def test_failed_step_is_skipped_with_exit_code():
    out = _render([_failed_step()])
    assert "# SKIPPED (failed, exit=1): brew install java" in out
    assert "\nbrew install java\n" not in out


def test_blocked_step_is_commented_blocked():
    out = _render([_blocked_step()])
    assert "# BLOCKED: rm -rf /" in out
    # The dangerous command never appears on its own executable line.
    assert "\nrm -rf /\n" not in out


def test_manual_step_is_commented_manual():
    out = _render([_manual_step()])
    assert "# MANUAL STEP: Request VPN access from IT" in out


def test_other_status_is_skipped_with_status():
    step = PlanStep(
        description="Deferred step",
        command="echo later",
        status="pending",
    )
    out = _render([step])
    assert "# SKIPPED (pending): echo later" in out


def test_secret_is_redacted():
    step = PlanStep(
        description="Auth call",
        command='curl -H "Authorization: Bearer SECRET123" https://api',
        status="done",
        exit_code=0,
    )
    out = _render([step], secrets=["SECRET123"])
    assert "SECRET123" not in out
    assert "***REDACTED***" in out


def test_secret_redacted_in_commented_command():
    step = PlanStep(
        description="Failed auth call",
        command="login --token SECRET123",
        status="failed",
        exit_code=2,
    )
    out = _render([step], secrets=["SECRET123"])
    assert "SECRET123" not in out
    assert "***REDACTED***" in out


def test_secret_redacted_in_description_comment():
    """A token echoed into an LLM-generated description must not leak into the # line."""
    step = PlanStep(
        description="set token to SECRET123 then run",
        command="echo ok",
        status="done",
        exit_code=0,
    )
    out = _render([step], secrets=["SECRET123"])
    assert "SECRET123" not in out
    assert "***REDACTED***" in out


def test_secret_redacted_in_manual_step_description():
    """Manual (command is None) steps render the description twice; both must redact."""
    step = PlanStep(
        description="manually export SECRET123",
        command=None,
        status="pending",
    )
    out = _render([step], secrets=["SECRET123"])
    assert "SECRET123" not in out
    assert "# MANUAL STEP: manually export ***REDACTED***" in out.splitlines()


def test_hostile_multiline_description_cannot_escape_comment():
    step = PlanStep(
        description="safe\nrm -rf /",
        command="echo ok",
        status="done",
        exit_code=0,
    )
    out = _render([step])
    lines = out.splitlines()
    # The injected 'rm -rf /' must not appear as its own executable line.
    assert "rm -rf /" not in lines
    assert "# safe rm -rf /" in lines


def test_empty_plan_is_valid_script_with_no_commands():
    out = _render([])
    assert out.startswith("#!/usr/bin/env bash\n")
    assert "set -euo pipefail" in out
    # No step lines: every line is blank, a comment, the shebang, or the strict-mode line.
    header_lines = {"#!/usr/bin/env bash", "set -euo pipefail"}
    for line in out.splitlines():
        assert line == "" or line.startswith("#") or line in header_lines


def test_large_plan_emits_all_live_commands():
    plan = [
        PlanStep(
            description=f"step {i}",
            command=f"echo step-{i}",
            status="done",
            exit_code=0,
        )
        for i in range(120)
    ]
    out = _render(plan)
    for i in range(120):
        assert f"echo step-{i}" in out


def test_live_command_body_emitted_verbatim():
    step = PlanStep(
        description="Chained install",
        command="brew install x && brew install y | tee log.txt",
        status="done",
        exit_code=0,
    )
    out = _render([step])
    assert "brew install x && brew install y | tee log.txt" in out


# --- Node tests (mocked vault/settings/git) ---


def _patch_settings(mock_settings, git_auto_sync=True):
    settings = mock_settings.return_value
    settings.obsidian.git_auto_sync = git_auto_sync
    settings.bedrock.auth_token = None
    settings.bedrock.endpoint_url = None
    settings.slack.user_token = None
    return settings


@pytest.mark.asyncio
async def test_node_sets_executable_bit(write_state, tmp_path):
    with (
        patch("agent_ls.graph.nodes.emit_harness.ObsidianVault") as mock_vault_cls,
        patch("agent_ls.graph.nodes.emit_harness.get_settings") as mock_settings,
        patch("agent_ls.graph.nodes.emit_harness.GitSync") as mock_git_cls,
    ):
        target = tmp_path / "harness.sh"
        mock_vault = MagicMock()
        mock_vault.exists.return_value = False
        mock_vault.write.side_effect = lambda rel, content: (
            target.write_text(content),
            target,
        )[1]
        mock_vault.root = tmp_path
        mock_vault_cls.return_value = mock_vault

        _patch_settings(mock_settings)
        mock_git_cls.return_value = MagicMock()

        result = await emit_harness_node(write_state)

    assert stat.S_IMODE(target.stat().st_mode) == 0o755
    assert result["harness_path"] == str(target)
    assert len(result["obsidian_docs"]) == 1


@pytest.mark.asyncio
async def test_node_pushes_on_success(write_state, tmp_path):
    write_state["run_success"] = True
    target = tmp_path / "harness.sh"

    with (
        patch("agent_ls.graph.nodes.emit_harness.ObsidianVault") as mock_vault_cls,
        patch("agent_ls.graph.nodes.emit_harness.get_settings") as mock_settings,
        patch("agent_ls.graph.nodes.emit_harness.GitSync") as mock_git_cls,
    ):
        mock_vault = MagicMock()
        mock_vault.exists.return_value = False
        mock_vault.write.side_effect = lambda rel, content: (
            target.write_text(content),
            target,
        )[1]
        mock_vault.root = tmp_path
        mock_vault_cls.return_value = mock_vault

        _patch_settings(mock_settings)
        mock_git = MagicMock()
        mock_git.commit_and_push.return_value = True
        mock_git_cls.return_value = mock_git

        result = await emit_harness_node(write_state)

    mock_git.commit_and_push.assert_called_once()
    mock_git.commit_file.assert_not_called()
    assert result["harness_path"] == str(target)


@pytest.mark.asyncio
async def test_node_commits_locally_when_not_success(write_state, tmp_path):
    write_state["run_success"] = False
    target = tmp_path / "harness.sh"

    with (
        patch("agent_ls.graph.nodes.emit_harness.ObsidianVault") as mock_vault_cls,
        patch("agent_ls.graph.nodes.emit_harness.get_settings") as mock_settings,
        patch("agent_ls.graph.nodes.emit_harness.GitSync") as mock_git_cls,
    ):
        mock_vault = MagicMock()
        mock_vault.exists.return_value = False
        mock_vault.write.side_effect = lambda rel, content: (
            target.write_text(content),
            target,
        )[1]
        mock_vault.root = tmp_path
        mock_vault_cls.return_value = mock_vault

        _patch_settings(mock_settings)
        mock_git = MagicMock()
        mock_git_cls.return_value = mock_git

        await emit_harness_node(write_state)

    mock_git.commit_file.assert_called_once()
    mock_git.commit_and_push.assert_not_called()


@pytest.mark.asyncio
async def test_node_skips_git_when_disabled(write_state, tmp_path):
    target = tmp_path / "harness.sh"

    with (
        patch("agent_ls.graph.nodes.emit_harness.ObsidianVault") as mock_vault_cls,
        patch("agent_ls.graph.nodes.emit_harness.get_settings") as mock_settings,
        patch("agent_ls.graph.nodes.emit_harness.GitSync") as mock_git_cls,
    ):
        mock_vault = MagicMock()
        mock_vault.exists.return_value = False
        mock_vault.write.side_effect = lambda rel, content: (
            target.write_text(content),
            target,
        )[1]
        mock_vault.root = tmp_path
        mock_vault_cls.return_value = mock_vault

        _patch_settings(mock_settings, git_auto_sync=False)
        mock_git = MagicMock()
        mock_git_cls.return_value = mock_git

        result = await emit_harness_node(write_state)

    mock_git.commit_file.assert_not_called()
    mock_git.commit_and_push.assert_not_called()
    assert result["harness_path"] == str(target)


@pytest.mark.asyncio
async def test_node_swallows_expected_git_failure(write_state, tmp_path):
    """An expected git failure (e.g. vault is not a repo -> ValueError) must not
    fail the node: the harness is already written, git sync is best-effort."""
    target = tmp_path / "harness.sh"

    with (
        patch("agent_ls.graph.nodes.emit_harness.ObsidianVault") as mock_vault_cls,
        patch("agent_ls.graph.nodes.emit_harness.get_settings") as mock_settings,
        patch("agent_ls.graph.nodes.emit_harness.GitSync") as mock_git_cls,
    ):
        mock_vault = MagicMock()
        mock_vault.exists.return_value = False
        mock_vault.write.side_effect = lambda rel, content: (
            target.write_text(content),
            target,
        )[1]
        mock_vault.root = tmp_path
        mock_vault_cls.return_value = mock_vault

        _patch_settings(mock_settings)
        # GitSync(vault.root) raises ValueError when the vault is not a git repo.
        mock_git_cls.side_effect = ValueError("not a git repository")

        result = await emit_harness_node(write_state)

    # The harness is still emitted; the git failure is logged and swallowed.
    assert result["harness_path"] == str(target)
    assert "error" not in result


@pytest.mark.asyncio
async def test_node_does_not_swallow_programming_error(write_state, tmp_path):
    """A programming bug (TypeError) in the git path must surface, not be masked
    by an over-broad `except Exception`."""
    target = tmp_path / "harness.sh"

    with (
        patch("agent_ls.graph.nodes.emit_harness.ObsidianVault") as mock_vault_cls,
        patch("agent_ls.graph.nodes.emit_harness.get_settings") as mock_settings,
        patch("agent_ls.graph.nodes.emit_harness.GitSync") as mock_git_cls,
    ):
        mock_vault = MagicMock()
        mock_vault.exists.return_value = False
        mock_vault.write.side_effect = lambda rel, content: (
            target.write_text(content),
            target,
        )[1]
        mock_vault.root = tmp_path
        mock_vault_cls.return_value = mock_vault

        _patch_settings(mock_settings)
        mock_git_cls.side_effect = TypeError("programming bug")

        with pytest.raises(TypeError):
            await emit_harness_node(write_state)


@pytest.mark.asyncio
async def test_node_appends_collision_counter(write_state, tmp_path):
    written = {}

    def _write(rel, content):
        target = tmp_path / rel.replace("/", "_")
        target.write_text(content)
        written["rel"] = rel
        return target

    with (
        patch("agent_ls.graph.nodes.emit_harness.ObsidianVault") as mock_vault_cls,
        patch("agent_ls.graph.nodes.emit_harness.get_settings") as mock_settings,
        patch("agent_ls.graph.nodes.emit_harness.GitSync") as mock_git_cls,
    ):
        mock_vault = MagicMock()
        # Base name (no counter) already exists; the -001 variant is free.
        mock_vault.exists.side_effect = lambda rel: "-001.sh" not in rel
        mock_vault.write.side_effect = _write
        mock_vault.root = tmp_path
        mock_vault_cls.return_value = mock_vault

        _patch_settings(mock_settings, git_auto_sync=False)
        mock_git_cls.return_value = MagicMock()

        await emit_harness_node(write_state)

    assert written["rel"].endswith("-001.sh")


@pytest.mark.asyncio
async def test_node_returns_error_on_write_failure(write_state, tmp_path):
    with (
        patch("agent_ls.graph.nodes.emit_harness.ObsidianVault") as mock_vault_cls,
        patch("agent_ls.graph.nodes.emit_harness.get_settings") as mock_settings,
    ):
        mock_vault = MagicMock()
        mock_vault.exists.return_value = False
        mock_vault.write.side_effect = OSError("disk full")
        mock_vault.root = tmp_path
        mock_vault_cls.return_value = mock_vault

        _patch_settings(mock_settings)

        result = await emit_harness_node(write_state)

    assert "error" in result
    assert "harness_write_failed" in result["error"]
    assert "harness_path" not in result


@pytest.mark.asyncio
async def test_node_redacts_settings_secrets(tmp_path):
    from langchain_core.messages import HumanMessage

    state = {
        "messages": [HumanMessage(content="setup")],
        "user_context": UserContext(team="payments"),
        "intent": "setup",
        "plan": [
            PlanStep(
                description="Auth",
                command="login --token TOKENXYZ",
                status="done",
                exit_code=0,
            )
        ],
        "current_step": 1,
        "execution_log": [],
        "approval_pending": None,
        "obsidian_docs": [],
        "slack_results": [],
        "error": None,
        "share_channel": None,
        "share_result": None,
        "extracted_urls": [],
        "processed_message_ids": [],
        "run_success": True,
    }
    target = tmp_path / "harness.sh"

    with (
        patch("agent_ls.graph.nodes.emit_harness.ObsidianVault") as mock_vault_cls,
        patch("agent_ls.graph.nodes.emit_harness.get_settings") as mock_settings,
        patch("agent_ls.graph.nodes.emit_harness.GitSync") as mock_git_cls,
    ):
        mock_vault = MagicMock()
        mock_vault.exists.return_value = False
        mock_vault.write.side_effect = lambda rel, content: (
            target.write_text(content),
            target,
        )[1]
        mock_vault.root = tmp_path
        mock_vault_cls.return_value = mock_vault

        settings = mock_settings.return_value
        settings.obsidian.git_auto_sync = False
        settings.bedrock.auth_token = "TOKENXYZ"
        settings.bedrock.endpoint_url = None
        settings.slack.user_token = None
        mock_git_cls.return_value = MagicMock()

        await emit_harness_node(state)

    content = target.read_text()
    assert "TOKENXYZ" not in content
    assert "***REDACTED***" in content


@pytest.mark.asyncio
async def test_node_does_not_redact_endpoint_url(tmp_path):
    """The Bedrock endpoint URL is a legitimate command substring, not a secret."""
    from langchain_core.messages import HumanMessage

    state = {
        "messages": [HumanMessage(content="setup")],
        "user_context": UserContext(team="payments"),
        "intent": "setup",
        "plan": [
            PlanStep(
                description="Probe models",
                command="curl https://bedrock.example.com/v1/models",
                status="done",
                exit_code=0,
            )
        ],
        "current_step": 1,
        "execution_log": [],
        "approval_pending": None,
        "obsidian_docs": [],
        "slack_results": [],
        "error": None,
        "share_channel": None,
        "share_result": None,
        "extracted_urls": [],
        "processed_message_ids": [],
        "run_success": True,
    }
    target = tmp_path / "harness.sh"

    with (
        patch("agent_ls.graph.nodes.emit_harness.ObsidianVault") as mock_vault_cls,
        patch("agent_ls.graph.nodes.emit_harness.get_settings") as mock_settings,
        patch("agent_ls.graph.nodes.emit_harness.GitSync") as mock_git_cls,
    ):
        mock_vault = MagicMock()
        mock_vault.exists.return_value = False
        mock_vault.write.side_effect = lambda rel, content: (
            target.write_text(content),
            target,
        )[1]
        mock_vault.root = tmp_path
        mock_vault_cls.return_value = mock_vault

        settings = mock_settings.return_value
        settings.obsidian.git_auto_sync = False
        settings.bedrock.auth_token = None
        settings.bedrock.endpoint_url = "https://bedrock.example.com"
        settings.slack.user_token = None
        mock_git_cls.return_value = MagicMock()

        await emit_harness_node(state)

    content = target.read_text()
    # The live command is emitted verbatim and uncommented, not corrupted.
    assert "curl https://bedrock.example.com/v1/models" in content.splitlines()
    assert "***REDACTED***" not in content


@pytest.mark.asyncio
async def test_node_sanitizes_team_path_separators(tmp_path):
    """A `team` containing path separators is slugified, not used verbatim in the path."""
    from langchain_core.messages import HumanMessage

    written = {}

    def _write(rel, content):
        written["rel"] = rel
        target = tmp_path / "logs"
        target.mkdir(parents=True, exist_ok=True)
        out = target / rel.split("/")[-1]
        out.write_text(content)
        return out

    state = {
        "messages": [HumanMessage(content="setup")],
        "user_context": UserContext(team="../../../../tmp/evil"),
        "intent": "setup",
        "plan": [_live_step()],
        "current_step": 1,
        "execution_log": [],
        "approval_pending": None,
        "obsidian_docs": [],
        "slack_results": [],
        "error": None,
        "share_channel": None,
        "share_result": None,
        "extracted_urls": [],
        "processed_message_ids": [],
        "run_success": False,
    }

    with (
        patch("agent_ls.graph.nodes.emit_harness.ObsidianVault") as mock_vault_cls,
        patch("agent_ls.graph.nodes.emit_harness.get_settings") as mock_settings,
        patch("agent_ls.graph.nodes.emit_harness.GitSync") as mock_git_cls,
    ):
        mock_vault = MagicMock()
        mock_vault.exists.return_value = False
        mock_vault.write.side_effect = _write
        mock_vault.root = tmp_path
        mock_vault_cls.return_value = mock_vault

        _patch_settings(mock_settings, git_auto_sync=False)
        mock_git_cls.return_value = MagicMock()

        result = await emit_harness_node(state)

    # No error: the slugified name stays inside logs/.
    assert "error" not in result
    rel = written["rel"]
    # Path separators from the team value are gone; the file is a single name in logs/.
    assert rel.startswith("logs/")
    filename = rel[len("logs/"):]
    assert "/" not in filename
    # Slashes were replaced, so the value can no longer traverse out of logs/.
    assert "tmp_evil" in filename
    assert (tmp_path / rel).resolve().is_relative_to((tmp_path / "logs").resolve())
